### ISSUE TITLE
[Enhancement] create the middleware package

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/api-proxy-middleware#1]
1. This repository should be an NPM package that exports the behavior currently located at the blog-front repository:
https://github.com/greenpress/blog-front/blob/master/server/api-proxy.js

2. Also, the exported function should auto-generate configuration from environment variables, while can get a manual configuration object.

3. this package should be published as `@greenpress/api-proxy-middleware`.

**Comment by or-yam** [comment]
Should we pass the config object as a parameter to the proxy function ?

**Comment by davidmeirlevy** [comment]
@or-yam only the config this function needs.
